CREATE TABLE informacion (
    id int NOT NULL AUTO_INCREMENT,
    fecha TIMESTAMP,
    nombre varchar(255) NOT NULL,
    apellidopaterno varchar(255) NOT NULL,
    apellidomaterno varchar(255) NOT NULL,
    celular varchar(20),
    email varchar(255),
    aceptoterminoscondicionescel varchar(20),
    historialcrediticio varchar(255),
    conocimientodelcliente varchar(255),
    curp varchar(255),
    rfc varchar(20),
    cp varchar(20),
    estado varchar(255),
    municipio INT,
    ciudad varchar(255),
    colonia varchar(255),
    calle varchar(255),
    numeroexterior varchar(255),
    numerointerior varchar(255),
    parentesco varchar(255),
    referenciapellido varchar(255),
    telfijoreferencia varchar(255),
    salarioneto varchar(255),
    ocupacion varchar(255),
    deudas varchar(255),
    frecuenciadepago varchar(255),
    fechadevencimiento varchar(255),
    bancotarjeta varchar(255),
    dineroquenecesita varchar(255),
    fechadepagoen varchar(255),
    totalaprestar varchar(255),
    aceptoterminoscondicionescontrato varchar(255),
    pictures1 varchar(255),
    pictures2 varchar(255),
    aceptocontrato varchar(255),
    contrasena varchar(255),
    PRIMARY KEY (id)
);


ALTER TABLE informacion ADD sugerencia varchar(255);
ALTER TABLE informacion ADD edad varchar(255);