
import React, { Component } from "react";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import "../styles/login.css";


class AvisodePrivacidad extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <NavBar location={this.props.history} />
        <section id="preguntas">
          <div className="container">
            <div className="row">
              <div className="col-sm padding-preguntas">
                 <h3 className="title-bold">Aviso de privacidad</h3>
                 <div className="container-parrafo-completo">
                    <p className="color-gray-tex">Fecha última de Actualización: 14 de octubre de 2020.</p><br/><br/>
                    <p className="color-gray-tex">En cumplimiento a lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de Particulares (LFPDPPP), en adelante LEY, su reglamento y demás disposiciones aplicables, se pone a disposición de los interesados (en lo sucesivo el “USUARIO”) que por cualquier motivo y/o medio entreguen a <b>AREZ FINANCIERA S.A. de C.V., SOFOM, E.N.R.,</b> (en lo sucesivo <b>“PRESTIFY”</b>), información personal, el presente:</p><br/><br/>
                    <p className="color-gray-tex"><b>AVISO DE PRIVACIDAD</b></p><br/><br/>
                    <p className="color-gray-tex"><b>1. Responsable de los datos recabados</b></p>
                    <p className="color-gray-tex"><b>AREZ FINANCIERA S.A. de C.V., SOFOM, E.N.R., </b> sociedad mercantil que cuenta con el nombre comercial de <b>PRESTIFY</b>, señala su domicilio el ubicado en  Av. Nuevo León #213 - 602 Col. Condesa, Cuauhtémoc, C.P. 06100, Cuidad de México. Es el responsable del tratamiento y protección de sus datos personales.</p>
                    <p className="color-gray-tex">El presente Aviso detalla la forma en que <b>PRESTIFY</b> utiliza sus datos personales y los derechos que usted tiene, para efectos de otorgarle un préstamo en línea a través de nuestra plataforma <a href="https://prestify.mx/" target="_self">www.prestify.mx</a>, <b>PRESTIFY</b> podrá obtener de manera directa o indirecta sus datos personales, sea por medio de llamada telefónica, página de internet, o terceros autorizados para tales efectos.</p><br></br>
                    <p className="color-gray-tex"><b>2. Datos personales y personales sensibles proporcionados por el USUARIO que serán sometidos al tratamiento correspondiente.</b></p><br></br>
                    <p className="color-gray-tex"><b>2.1.</b> Datos de identificación: Nombre; apellido paterno; apellido materno; género; fecha de nacimiento; entidad federativa de nacimiento; estado civil; CURP; clave OCR, clave de elector o número de identificación de elector; RFC.</p>
                    <p className="color-gray-tex"><b>2.2.</b> Datos de contacto: Dirección de correo electrónico; número de teléfono móvil; número de teléfono fijo; dirección de residencia.</p>
                    <p className="color-gray-tex"><b>2.3.</b> Datos financieros: Datos bancarios (número de tarjeta, número de seguridad), ingreso mensual, fecha de próximo pago, gasto promedio mensual, número de cuentas bancarias, saldos en cuentas bancarias, nombre del beneficiario de cuentas bancarias, fechas de pago, historial bancario; tipo de vivienda incluyendo su modalidad y fechas de inicio de residencia.</p>
                    <p className="color-gray-tex"><b>2.4.</b> Datos Laborales: Empresa donde labora actualmente, último nivel de estudios, cargo, fecha de inicio del último empleo, dirección de trabajo, sector empresarial.</p>
                    <p className="color-gray-tex"><b>2.5.</b> Registros informáticos relacionados con actividades y comportamiento en internet: Horario de navegación, periodo de tiempo de navegación en nuestro sitio web, secciones consultadas y páginas web que visitó antes de ingresar a nuestro Sitio, dirección IP.</p>
                    <p className="color-gray-tex"><b>2.6.</b> Datos de terceros: Número de dependientes, referencias personales y/o laborales, en los que se incluye: nombre del referenciado, número telefónico y parentesco con el titular del solicitante del crédito.</p>
                    <p className="color-gray-tex"> Los datos antes mencionados serán recabados con fines inherentes al crédito solicitado y/o para obtener datos estadísticos.</p><br></br>
                    <p className="color-gray-tex"> <b>PRESTIFY</b> no obtiene proactivamente ningún dato que pudiera ser considerado como sensible bajo la LEY (datos ideológicos, sobre opiniones políticas, afiliación sindical, de salud, vida sexual y origen étnico o racial). Por lo anterior, le pedimos que no sea enviado ningún dato considerado como sensible. De cualquier modo y en caso de que detectemos que usted nos ha proporcionado algún dato considerado como sensible, en la medida en que este resulte necesario para el mantenimiento de nuestra relación con usted, será tratado con la seguridad y precauciones previstas en la LEY. De no ser necesario, este será suprimido en los términos de LEY.</p><br></br>

                    <p className="color-gray-tex"><b>3. Finalidad de los datos solicitados.</b></p><br></br>
                    <p className="color-gray-tex"><b>PRESTIFY</b> solicita al USUARIO datos personales con dos tipos de finalidades:</p>
                    <p className="color-gray-tex">Finalidades Primarias: Corresponden al origen de la relación contractual entre el USUARIO y PRESTIFY siendo las que resultan necesarias para llevar a cabo y mantener la relación de negocio que tenemos con los Usuarios;</p>
                    <p className="color-gray-tex"><b> 1.</b> Validación de Identidad de forma directa y/o a través de terceros nacionales o extranjeros.</p>
                    <p className="color-gray-tex"><b> 2.</b> Evaluación de perfil de riesgo y crediticio de forma directa y/o a través de terceros nacionales o extranjeros.</p>
                    <p className="color-gray-tex"><b> 3.</b> Celebración de Contratos de Crédito.</p>
                    <p className="color-gray-tex"><b> 4.</b> Detección y Manejo de fraudes de forma directa y/o a través de terceros nacionales o extranjeros.</p>
                    <p className="color-gray-tex"><b> 5.</b> Seguridad de la infraestructura proporcionada a nuestros Clientes.</p>
                    <p className="color-gray-tex"><b> 6.</b>  Requerimientos de pago y/o cumplimiento de sus obligaciones.</p>
                    <p className="color-gray-tex"><b> 7.</b>  Ceder o enajenar, parcial o totalmente los derechos a favor de <b>PRESTIFY</b> que se deriven de los Contratos que se hubieren celebrado.</p>
                    <p className="color-gray-tex"><b> 8.</b>  Administración de la relación contractual con nuestros Clientes.</p>
                    <p className="color-gray-tex"><b> 9.</b>  Recibir y atender las preguntas que realizan nuestros Clientes sobre los servicios.</p>
                    <p className="color-gray-tex"><b> 10.</b>  Vigilar la calidad de nuestros servicios.</p><br></br>
                    <p className="color-gray-tex">Finalidades Complementarias: Aquellas que no son indispensables para la prestación del servicio, pero nos permiten y facilitan brindarle una mejor atención a los usuarios:</p>
                    <p className="color-gray-tex"><b> 1.</b>  Ofrecimiento de productos y/o servicios análogos y varios a los previamente solicitados.</p>
                    <p className="color-gray-tex"><b> 2.</b>  Para fines comerciales y publicitarios relacionados con los productos y servicios ofrecidos por <b>PRESTIFY</b> y/o partes relacionadas.</p>
                    <p className="color-gray-tex"><b> 3.</b>  Evaluación de atención al cliente </p><br></br>
                    <p className="color-gray-tex">Asimismo, <b>PRESTIFY</b>, deberá recabar adicionalmente del Usuario los datos necesarios para cumplir con las disposiciones aplicables en materia de prevención y detección de operaciones que pudieran favorecer, prestar ayuda, auxilio o cooperación de cualquier especie para la comisión de los delitos previstos en los artículos 139; 148 Bis y/o 400 Bis del Código Penal Federal, fracción IV del artículo 17 de la Ley Federal para la Prevención e Identificación de Operaciones con</p>
                    <p className="color-gray-tex">Recursos de Procedencia Ilícita (LFPIORPI), aplicables a los sujetos distintos a las Entidades Financieras.</p>
                    <p className="color-gray-tex"><b>PRESTIFY</b> otorga por medio del presente Aviso de Privacidad el derecho al USUARIO de manifestar su negativa respecto al uso y tratamiento de sus Datos Personales, cuando considere que la información proporcionada, NO cumple ninguna de las funciones anteriormente descritas dentro de los numerales anteriores, o bien, que no es necesaria para el establecimiento de la relación contractual.</p>
                    <p className="color-gray-tex">El USUARIO deberá informar a PRESTIFY sobre cualquier limitación en el uso de sus Datos Personales al momento en el que el presente Aviso de Privacidad sea puesto a su disposición; entendiéndose que la aceptación del presente Aviso o cualquier gestión tendiente a la obtención de los servicios y contenidos se entiende como de entera conformidad del uso de sus Datos Personales por parte del <b>USUARIO</b>. Lo anterior, sin perjuicio de la aplicación del Derecho de Revocación de Consentimiento previamente otorgado por parte del USUARIO o bien de ejercer sus derechos de acceso, rectificación, cancelación u oposición al uso de sus Datos en términos de la LEY, derechos que en todo caso serán garantizados por PRESTIFY. La negativa para el uso de sus datos personales para estas finalidades no podrá ser un motivo para que le neguemos los servicios y productos que solicita o contrata con nosotros.</p>
                    <p className="color-gray-tex"><b>4. Obtención y tratamiento de los datos personales.</b></p>
                    <p className="color-gray-tex">El USUARIO, mediante el ingreso de sus Datos Personales en la Página Web, autoriza expresamente a <b>PRESTIFY</b> y/o su personal administrativo, así como a su matriz: Innovative Digital Finance (“ID Finance”) a derivar a partir de dichos otorgados, cualquier número o clave de identificación personal directamente vinculado con la prestación del servicio y con la verificación de la identidad del USUARIO.</p><br></br>
                    <p className="color-gray-tex"><b>PRESTIFY</b> procesará y protegerá los datos del USUARIO a través de medios digitales, técnicos y administrativos para garantizar un óptimo nivel de seguridad. De manera paralela, <b>PRESTIFY</b> guardará la información otorgada por el USUARIO con secrecía y confidencialidad, comprometiéndose en la medida de lo posible a adoptar todas las medidas de control y seguridad necesarios para evitar la alteración, uso, tratamiento, pérdida y/o acceso por terceros no autorizados.</p>
                    <p className="color-gray-tex">El USUARIO expresamente declara que toda la información que ponga a disposición de  <b>PRESTIFY</b> es exacta, cierta y libre de mala fe o vicios, liberando expresamente por este acto a  <b>PRESTIFY</b> de cualquier responsabilidad con relación a la veracidad dicha información misma que incluye los Datos Personales, laborales, patrimoniales y referencias personales del USUARIO.</p>
                    <p className="color-gray-tex">Los Datos de carácter personal recogidos por <b>PRESTIFY</b>  serán almacenados en sus servidores y serán utilizados de acuerdo con los fines enumerados en el numeral 3 del presente Aviso de Privacidad.</p>
                    <p className="color-gray-tex">Si durante el proceso de solicitud, el USUARIO aceptara voluntariamente la validación de su cuenta bancaria mediante el servicio “Instator” o similares, otorgando acceso a sus datos financieros o patrimoniales, el USUARIO autoriza a <b>PRESTIFY</b> a almacenar la información relativa a las transacciones realizadas durante los últimos 180 días mismos que serán utilizados de acuerdo con los fines enumerados en la cláusula 3 del presente Aviso y de conformidad con la legislación bancaria aplicable.</p>
                    <p className="color-gray-tex">El presente Aviso de Privacidad corresponde a <a href="https://prestify.mx/" target="_self">www.prestify.mx</a>; así como a todos los medios disponibles para obtener Datos Personales por parte del USUARIO a los que <b>PRESTIFY</b> acuda.</p>
                    <p className="color-gray-tex"><b>5. Transferencia de Datos</b></p>
                    <p className="color-gray-tex">El uso de los Datos Personales del USUARIO estará regido y limitado por el presente Aviso de Privacidad, conservándolos por el tiempo que las disposiciones legales aplicables señalen.</p>
                    <p className="color-gray-tex">I. Para cumplir con las finalidades primarias señaladas en el numeral 3 del presente Aviso,  <b>PRESTIFY</b> podrá transferir sus datos, sin que se requiera su consentimiento expreso, en conformidad con lo dispuesto por el artículo 37 de la Ley a:</p>
                    <p className="color-gray-tex">a. A todas las Sociedades que integran el grupo ID Finance y las demás entidades controladoras, subsidiarias o afiliadas.</p>
                    <p className="color-gray-tex">b. Autoridades judiciales, gubernamentales, financieras o fiscales, para dar cumplimiento con las disposiciones legales correspondientes, así como para el esclarecimiento de incidentes o  ejercicio de algún derecho.</p>
                    <p className="color-gray-tex">c. Empresa aseguradora, con la finalidad de celebración de póliza de desempleo, incapacidad o muerte. Estos datos se compartirán únicamente al contratar el seguro.</p>
                    <p className="color-gray-tex">d. Sociedades de información crediticia</p><br></br>
                    <p className="color-gray-tex"><b>I.</b>Adicionalmente, el USUARIO autoriza la transferencia de datos personales a terceros nacionales y extranjeros proveedores de servicios que nos apoyan con algún proceso, con el estricto propósito de corroborar su identidad, así como de evaluar su perfil de riesgo y crediticio de forma directa o indirecta durante el proceso de contratación y posterior al mismo para efectos de actualización.</p>
                    <p className="color-gray-tex"><b>II.</b>El USUARIO autoriza la transferencia de los Datos Financieros (nombre del titular número de tarjeta, número de seguridad, y fecha de vencimiento) a Grupo Conektame, S.A. de C.V. (Conekta) con domicilio en Avenida Nuevo León número 254, interior 404, Colonia Hipódromo Condesa, Delegación Cuauhtémoc, C.P. 06100 de la Ciudad de México, quien cuenta con Certificación PCI (Payment Card Industry) con el estricto propósito de que Conekta pueda proveer los servicios de intermediación en el procesamiento de los pagos que el USUARIO realice a favor de <b>PRESTIFY</b></p>
                    <p className="color-gray-tex"><b>III.</b> Agencias de cobranza: en el ejercicio de los derechos generados como consecuencia del contrato de préstamo entre <b>PRESTIFY </b> y el USUARIO, los Datos Personales de éste serán transferidos a las Agencias de Cobranza con las que PRESTIFY tenga celebrados convenios para la gestión de cuentas, las cuales podrán consultar los Clientes en https://www.prestify.mx/agencias-de-cobranza/. En todos los casos, los Datos Personales transferidos serán los estrictamente necesarios para el ejercicio de los derechos de cobro contractuales. En particular, incluirán la información de contacto del prestatario, así como cualquier cantidad adeudada como consecuencia del contrato de préstamo entre <b>PRESTIFY</b> y el USUARIO.</p>
                    <p className="color-gray-tex">En el evento de transferencia a terceros nacionales o extranjeros, <b>PRESTIFY</b> garantiza que los receptores respetarán los datos otorgados expresamente para las finalidades de tratamiento enunciadas. Dichas terceras partes podrán dedicarse, a la realización de actividades de un giro similar a PRESTIFY o estar ligadas a PRESTIFY por una relación contractual. Lo anterior incluye más no se limita a Entidades y Dependencias gubernamentales, Despachos de Cobranza, Entidades Financieras (nacionales o extranjeras), Instituciones de Seguros y/o Fianzas, y personas físicas y morales que le presten servicios a PRESTIFY. Dichas transferencias tendrán como finalidad:</p>
                    <p className="color-gray-tex"><b>1.</b> Cumplir con la Legislación en materia de Protección de Datos Personales en Posesión de Particulares;</p>
                    <p className="color-gray-tex"><b>2.</b>El correcto origen, mantenimiento y/o cumplimiento de las obligaciones y derechos contraídos por medio de los Contratos celebrados entre las partes;</p>
                    <p className="color-gray-tex"><b>3.</b> Garantía y protección de los derechos de pago de <b>PRESTIFY</b>;</p>
                    <p className="color-gray-tex"><b>4.</b> Garantizar los derechos contractuales de cualquier índole pertenecientes a <b>PRESTIFY</b>;</p>
                    <p className="color-gray-tex"><b>5.</b> La protección de los derechos del USUARIO;</p>
                    <p className="color-gray-tex"><b>6.</b> Publicidad y promoción de los productos financieros que <b>PRESTIFY</b> ofrezca al USUARIO.</p>
                    <p className="color-gray-tex">Para el caso de las finalidades descritas en este último numeral, contactaremos al USUARIO para otorgarle la posibilidad de manifestar su negativa respecto al uso y tratamiento de sus Datos Personales.</p>
                    <p className="color-gray-tex">Fuera de los anteriores supuestos limitativos, el USUARIO deberá otorgar su expreso consentimiento para la transferencia de sus datos personales.</p>
                    <p className="color-gray-tex"><b>7. Limitación del uso o transferencia de datos personales</b></p>
                    <p className="color-gray-tex">En caso de que los Datos Personales ingresados por el USUARIO no sean imprescindibles para el cumplimiento de las obligaciones resultantes de la relación jurídica existente entre el USUARIO y <b>PRESTIFY</b>, el primero tendrá el derecho de requerir a <b>PRESTIFY</b> que limite la divulgación, uso y/o transferencia de dichos datos mediante solicitud expresa siguiendo el procedimiento mencionado en la cláusula 10 del presente Aviso de Privacidad.</p>
                    <p className="color-gray-tex"><b>8. Revocación de consentimiento.</b></p>
                    <p className="color-gray-tex">El USUARIO podrá en cualquier momento informar a  <b>PRESTIFY</b> su determinación de revocar el consentimiento que previamente se hubiere otorgado para el tratamiento de los datos personales de acuerdo con las finalidades descritas en el presente Aviso de Privacidad. Lo anterior, con la finalidad de que  <b>PRESTIFY</b> interrumpa el tratamiento de estos y siempre y cuando el consentimiento que se pretenda revocar no se encuentre ligado a una relación jurídica contractual u operación vigente y activa de cualquier índole pactada con  <b>PRESTIFY</b>, en términos de la LEY o pacto expreso entre  <b>PRESTIFY</b> y el USUARIO. La revocación del consentimiento no surtirá efectos retroactivos en ningún momento. La revocación de consentimiento se hará efectiva a través de los medios y procedimientos descritos en la cláusula 10 del presente Aviso de Privacidad.</p>
                    <p className="color-gray-tex"><b>9.</b>Ejercicio de los derechos de Acceso, Rectificación, Cancelación u Oposición (derechos ARCO).</p>
                    <p className="color-gray-tex">El USUARIO será responsable de la exactitud, veracidad, autenticidad y vigencia de sus datos. El USUARIO de <b>PRESTIFY</b> tendrá derecho de acceder a sus datos personales recabados, a hacer correcciones a los mismos en caso de ser estos inexactos o incompletos, a eliminar sus datos cuando considere que no son necesarios para alguna de las finalidades señaladas en el presente Aviso de Privacidad cuando esto sea legalmente procedente, y a oponerse al uso/tratamiento de sus datos, en términos de la LEY y las disposiciones aplicables en la materia.</p><br></br>
                    <p className="color-gray-tex"><b>10. Procedimiento para la limitación del uso o transferencia de Datos Personales, el ejercicio de los derechos ARCO y la revocación del consentimiento.</b></p>
                    <p className="color-gray-tex">El USUARIO podrá limitar el uso o transferencia, ejercer sus derechos ARCO y revocar su consentimiento respecto al uso de sus Datos Personales, mediante solicitud expresa, misma que podrá ser obtenida a través de la Unidad Especializada de Atención a Usuarios de <b>PRESTIFY</b>, la cual deberá ser solicitada de forma electrónica mediante correo electrónico <b>atencion@prestify.mx</b> dirigido al oficial de privacidad, quien en un plazo máximo de 10 días hábiles dará contestación a su correo indicando el procedimiento para el ejercicio de esos derechos.</p>
                    <p className="color-gray-tex">Asimismo, el oficial de privacidad podrá resolver cualquier duda que surja al respecto del ejercicio de estos derechos.</p>
                    <p className="color-gray-tex">Usted tendrá siempre la opción de limitar la utilización de sus datos personales con fines de comercialización, inscribiéndose en el Registro Público de Usuarios (REUS) a cargo de Comisión Nacional para la Protección y de Defensa de los Usuarios de Servicios Financieros.</p>
                    <p className="color-gray-tex"><b>PRESTIFY</b> responderá a la solicitud, dentro del plazo de 20 (veinte) días hábiles contados a partir del día siguiente a la recepción de la solicitud. La respuesta se hará llegar al USUARIO a través del mismo canal por el cual fue ingresada (presencial o electrónicamente) dentro del plazo anterior. PRESTIFY tendrá la obligación de dar cumplimiento a los acuerdos señalados en el escrito de contestación al Usuario en un plazo máximo de 15 (quince) días hábiles posteriores a su comunicación al USUARIO.</p>
                    <p className="color-gray-tex">El USUARIO, en caso de considerar que sus Derechos han sido vulnerados, podrá presentar ante el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI) una solicitud de protección de datos por la respuesta recibida o falta de respuesta de PRESTIFY. Dicha solicitud deberá presentarse por el USUARIO dentro de los 15 días hábiles siguientes a la fecha en que se comunique la respuesta al USUARIO por parte PRESTIFY, y se sujetará a lo previsto en la LEY.</p><br></br>
                    <p className="color-gray-tex"><b>11. Negativa de Tratamiento</b></p>
                    <p className="color-gray-tex"><b>El USUARIO, en caso de obtener una negativa del cese en el tratamiento ante la revocación del consentimiento por parte de <b>PRESTIFY</b>, podrá iniciar el procedimiento de Oposición, el cual forma parte de los derechos ARCO. Asimismo, puede realizar una denuncia ante el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI)</b></p>
                    <p className="color-gray-tex"><b>12. Seguridad.</b></p>
                    <p className="color-gray-tex">Todos los datos introducidos en el sitio web están protegidos por la tecnología de encriptación <b>INSERT ENCRYPTION TECHNOLOGY SLL (Secure Locker Layer)</b>.</p>
                    <p className="color-gray-tex">El sitio web utiliza técnicas de seguridad de la información generalmente aceptadas en la industria, tales como firewalls, procedimientos de control de acceso y mecanismos criptográficos, todo ello con el objeto de evitar el acceso no autorizado a los datos. Para lograr estos fines, el USUARIO acepta que el prestador obtenga datos para efectos de la correspondiente autenticación de los controles de acceso. Todo proceso de contratación o que conlleve la introducción de datos personales de carácter alto serán siempre transmitidos mediante protocolo de comunicación segura, de tal forma que ningún tercero tenga acceso a la información transmitida vía electrónica. Cuando sea estrictamente necesario el tratamiento de los Datos Personales mediante medios humanos, <b>PRESTIFY</b> se compromete a utilizar la adecuada segmentación para evitar en todo lo posible una innecesaria exposición de dichos datos.</p>
                    <p className="color-gray-tex"><b>13. Cookies y redes sociales.</b></p>
                    <p className="color-gray-tex">El USUARIO que tenga acceso a nuestra página web, acuerda recibir las Cookies que les transmitan los servidores de <b>PRESTIFY</b>. “Cookie” significa un archivo de datos que se almacena en el disco duro de la computadora del USUARIO cuando este tiene acceso a nuestra página web.</p>
                    <p className="color-gray-tex">Las Cookies pueden contener información tal como la identificación proporcionada por el USUARIO o información para rastrear las páginas que el USUARIO ha visitado. Una Cookie no puede leer los datos o información del disco duro del USUARIO ni leer las Cookies creadas por otros sitios o páginas.</p>
                    <p className="color-gray-tex"><b>PRESTIFY</b> no tiene control alguno sobre los sitios web mostrados como resultados de búsquedas o enlaces que se incluyen en nuestra página web. Es posible que estos sitios independientes envíen sus propias cookies u otros archivos a su equipo, recopilen datos o le soliciten que envíe información personal.</p>
                    <p className="color-gray-tex">Las redes sociales constituyen una plataforma de comunicación y de interconexión entre plataformas digitales de los distintos usuarios, por lo tanto, son ajenas a <b>PRESTIFY</b>, por ello, no se encuentran bajo su responsabilidad.</p>
                    <p className="color-gray-tex">La información y datos proporcionados por el USUARIO dentro a las redes sociales de las cuales <b>PRESTIFY</b>, sea USUARIO, no constituyen en ningún momento parte de la información personal o sensible sujeta a la protección de este Aviso de Privacidad, siendo responsabilidad de la empresa prestadora de esa plataforma y de quien lo publica.</p>
                    <p className="color-gray-tex"><b>14. Medios de notificación de cambio en el Aviso.</b></p><br></br>
                    <p className="color-gray-tex"><b>PRESTIFY</b> podrá realizar cambios en el presente Aviso a efecto de dar cumplimiento a reformas legislativas, requerimientos de autoridades y modificación a políticas internas o estructura corporativa.</p>
                    <p className="color-gray-tex">Cualquier cambio y/o modificación total o parcial al presente Aviso de Privacidad se dará a conocer a través de alguno de los siguientes medios:</p>
                    <p className="color-gray-tex">a) Comunicado por escrito publicado dentro de las instalaciones de <b>PRESTIFY</b></p>
                    <p className="color-gray-tex">b) Mensaje (SMS) enviado a su correo electrónico o a su teléfono móvil</p>
                    <p className="color-gray-tex">c) Mensaje dado a conocer a través cualquier medio electrónico que utilice para celebrar operaciones con <b>PRESTIFY</b></p>
                    <p className="color-gray-tex">d) Comunicado a través del sitio de internet de <b>PRESTIFY</b>: <b>www.prestify.mx</b></p>
                    <p className="color-gray-tex"><b>15. Contacto</b></p>
                    <p className="color-gray-tex">Si tiene alguna duda sobre el contenido, interpretación o alcance del presente Aviso de Privacidad puede acudir a la Unidad Especializada de Atención de Usuarios ubicada en Av. Nuevo León #213 - 602 Col. Condesa, Cuauhtémoc, C.P. 06100, Cuidad de México. O bien enviar un correo electrónico a: <b>atencion@prestify.mx</b></p>
                </div>
              </div>
            </div>
          </div>
         </section>
        <Footer location={this.props.history} />
      </div>
    );
  }
}

export default AvisodePrivacidad;
