
import React, { Component } from "react";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import "../styles/login.css";


class Terminosycondiciones extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div>
        <NavBar location={this.props.history} />
        <section id="preguntas">
          <div className="container">
            <div className="row">
              <div className="col-sm padding-preguntas">
                 <h3 className="title-bold-big">TÉRMINOS Y CONDICIONES DE USO Y PRIVACIDAD DEL SITIO</h3>
                  <div className="container-parrafo-completo">
                    <p className="color-gray-tex">Fecha última de Actualización: 19 de octubre de 2020.</p><br/><br/>
                    <p className="color-gray-tex">El presente Convenio describe los términos y condiciones generales de uso y privacidad (los “Términos y Condiciones Generales”) <b>aplicables al uso de los servicios ofrecido AREZ FINANCIERA S.A. de C.V., SOFOM, E.N.R. </b>(en lo sucesivo <b>PRESTTO</b>) dentro del sitio <a href="https://prestify.mx/" target="_self">www.prestify.mx</a>  (el “Sitio”), los cuales serán referidos en el Sitio y en estos Términos y Condiciones Generales, indistintamente como <b>PRESTTO</b>. Cualquier persona que desee acceder y/o usar el sitio o los servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales, junto con todas las demás políticas y principios que rigen PRESTTO y que son incorporados al presente por referencia.</p>
                    <p className="color-gray-tex"><b>CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</b></p>
                    <p className="color-gray-tex">El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los presentes Términos y Condiciones Generales y en el Aviso de Privacidad, así como en los demás documentos incorporados a los mismos por referencia, previo a su inscripción como Cliente y/o Usuario del Portal <b>PRESTTO</b>.</p>
                    <p className="color-gray-tex"><b>LEGITIMACIÓN DE USO</b>.</p>
                    <p className="color-gray-tex">El acceso o utilización del Portal  PRESTTO expresan la adhesión plena y sin reservas del Usuario a los presentes Términos y Condiciones de Uso y Privacidad. A través del Portal www.prestify.mx, el Usuario se servirá y/o utilizará diversos servicios y contenidos (en lo sucesivo, los “Servicios y Contenidos”), puestos a disposición de los Clientes y/o Usuarios por <b> PRESTTO</b>  y/o por terceros proveedores de Servicios y Contenidos.</p>
                    <p className="color-gray-tex"><b>PRESTTO</b> tendrá el derecho a negar, restringir o condicionar al Usuario el acceso a las Páginas que integran el Portal, total o parcialmente, a su entera discreción, así como a modificar los Servicios y Contenidos de las Páginas en cualquier momento y sin necesidad de previo aviso. El Cliente y/o Usuario reconoce que no todos los Servicios y Contenidos están disponibles en todas las áreas geográficas y que algunos podrán ser utilizados solamente con posterioridad a su contratación, activación o registro previo por el Usuario y/o mediante el pago de una comisión, según se indique en las condiciones de contratación que se establezcan en la documentación respectiva.  <b>PRESTTO</b> no garantiza la disponibilidad y continuidad de la operación y utilidad del Portal en relación con cualquier actividad específica, independientemente del medio de acceso que utilice el Usuario incluido el de telefonía móvil.  <b>PRESTTO</b> no será responsable por daño o pérdida alguna de cualquier naturaleza que pueda ser causado debido a la falta de disponibilidad o continuidad de operación del Portal.</p>
                    <p className="color-gray-tex">El Usuario autoriza a <b>PRESTTO</b> y a sus proveedores de telefonía móvil, a enviarle mensajes de texto o SMS a través del equipo telefónico del Usuario para la autenticación de la identidad de aquel, en el entendido de que el envío de los mensajes de texto o SMS serán a demanda del Usuario.</p><br></br>
                    <p className="color-gray-tex">Sin que lo anterior implique de ninguna manera, autorización de parte del Usuario para recibir a través de ese medio información publicitaria de  <b>PRESTTO</b> ni de sus proveedores.</p><br></br>
                    <p className="color-gray-tex">Los Servicios y Contenidos únicamente estarán disponibles para personas que tengan la capacidad legal para contratarlos. No podrán utilizar los servicios las personas que no tengan esa característica, los menores de edad o Usuarios de  PRESTTO que hayan sido suspendidos temporalmente o inhabilitados definitivamente en relación con su comportamiento crediticio. Asi mismo, el Usuario, entendiendo por este término a aquella persona que accede mediante el uso de un equipo de cómputo y/o de comunicación al Portal, está de acuerdo en no utilizar dispositivos, programas de cómputo, software, o cualquier otro medio que pueda interferir tanto en las funcionalidades, actividades y/u operaciones del Portal como en las bases de datos y/o información que se contenga en el mismo.</p><br></br>
                    <p className="color-gray-tex"><b>1.DESCRIPCIÓN DEL PRODUCTO</b></p><br></br>
                    <p className="color-gray-tex"><b>AREZ FINANCIERA S.A. de C.V., SOFOM, E.N.R. /y/o  PRESTTO </b> procurarán ser los más leales a la descripción de la oferta, promoción o producto lanzado. <b>PRESTTO</b> no garantiza que las descripciones de los productos u otro contenido de este sitio sean exactos, completos, confiables, actualizados o contengan errores. Si un producto ofrecido en el Portal no es como se le describe, el único recurso que usted tendrá será contactar directamente a nuestra Unidad Especializada de Atención a Usuarios.</p><br></br>
                    <p className="color-gray-tex"><b>&nbsp;USO DE LA INFORMACIÓN PROPORCIONADA</b></p><br></br>
                    <p className="color-gray-tex">Es obligatorio completar el formulario de inscripción en todos sus campos con datos personales válidos para poder utilizar los servicios y contenidos que brinda <b>PRESTTO</b>. El Usuario deberá completarlo con información personal de manera exacta, precisa y verdadera (“Datos Personales”) y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. <b>PRESTTO</b> podrá utilizar diversos medios para identificar a sus Usuarios, pero  <b>PRESTTO</b> NO se responsabiliza por la certeza de los Datos Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.  <b>PRESTTO</b> se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. El Usuario accederá a su cuenta personal (“mi Cuenta”) mediante el ingreso de su clave y contraseña elegida (“Clave de Seguridad”). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad. La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario inscriba o posea más de una Cuenta. En caso de que  PRESTTO detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá cancelar, suspender o inhabilitarlas.</p>
                    <p className="color-gray-tex">El Usuario será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a  <b>PRESTTO</b>  en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Cuenta (incluyendo la reputación y calificaciones) bajo ningún título.</p>
                    <p className="color-gray-tex"><b>PRESTTO</b> se reserva el derecho de rechazar cualquier solicitud de registro o de cancelar un registro previamente aceptado, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.</p>
                    <p className="color-gray-tex">No obstante, en caso de que la aplicación sea rechazada por causas imputables al Usuario,  <b>PRESTTO</b> podrá mostrarles otras opciones que se ajusten a su capacidad de pago con la finalidad de facilitar el acceso al crédito, sin que esto signifique obligación por parte del solicitante de aceptar dichas opciones.</p>
                    <p className="color-gray-tex">Al utilizar el Sitio, el usuario se adhiere plenamente y sin reservas a los presentes Términos y Condiciones Generales. A través del Sitio, el usuario tendrá acceso y/o disposición de servicios, productos y contenidos varios (en adelante “Servicios y Contenidos”).  <b>PRESTTO</b> se reservará el derecho de negar, restringir o condicionar en cualquier momento al usuario el acceso total o parcial al Sitio de manera discrecional, pudiendo de igual manera modificar los “Servicios y Contenidos” del Sitio en todo momento y sin previo aviso. <b>PRESTTO</b> no garantiza en ningún momento la disponibilidad y continuidad de la operación, funcionalidad, utilidad y/o disponibilidad del Sitio y/o los “Servicios y Contenidos”, en relación con ninguna actividad específica.  <b>PRESTTO</b> no se responsabiliza por pérdida o daño alguno, sin importar su alcance o naturaleza, que resulte de la falta de continuidad o disponibilidad operativa del Sitio y/o de los “Servicios y Contenidos”.</p>
                    <br></br><p className="color-gray-tex"><b>2.  COMUNICADOS ELECTRÓNICOS</b></p>
                    <p className="color-gray-tex">Al enviar un e-mail a cualquier correo de  <b>PRESTTO</b>, se está comunicando con nosotros electrónicamente. Por lo tanto, el Usuario acepta recibir comunicados electrónicos por parte de <b>PRESTTO</b>. Los avisos que podremos emitir serán a través de: correo electrónico; por medio de colocar avisos en el Portal <b>PRESTTO</b>. El Usuario acepta que las divulgaciones que sean enviados mediante correo electrónico satisfacen los requerimientos legales.</p>
                    <br></br><p className="color-gray-tex"><b>3. PROMOCIONES ESPECIALES</b></p>
                    <p className="color-gray-tex"> <b>PRESTTO</b>  podrá lanzar promociones especiales mediante las cuales se podrán ofrecer distintos beneficios a sus Usuarios. La participación y aceptación de estas promociones corresponderá a criterios determinados por PRESTTO. En ningún momento  <b>PRESTTO</b>  se compromete a lanzar promociones especiales en fechas específicas o derivadas de alguna eventualidad. Los términos y condiciones específicos de las promociones especiales que  <b>PRESTTO</b>  ofrezcan, se comunicarán al momento del lanzamiento de la promoción y durante su vigencia, y se sujetarán a los presentes términos y condiciones y a las leyes mexicanas aplicables en la materia en lo que no se detalle.</p>
                    <br></br><p className="color-gray-tex"><b>4. PROPIEDAD INTELECTUAL</b></p>
                    <p className="color-gray-tex"><b>AREZ FINANCIERA S.A. de C.V., SOFOM, E.N.R.</b> y <b>PRESTTO</b> son Marcas Registradas que se encuentran protegidas por la Ley de la Propiedad Industrial tanto en México como en el extranjero según las leyes aplicables. La utilización, difusión, exhibición, explotación, comercialización o cualquier otro uso, sea parcial o total, de forma idéntica o que confunda en menor o mayor grado; sea por cualquier medio, incluyendo más no limitándose al impreso, magnético, óptico, electrónico o informático, está expresamente prohibido sin previa autorización por escrito del titular de los derechos de autor y/o marca correspondiente. Cualquier contravención a lo anteriormente expuesto o la legislación aplicable en materia de propiedad intelectual, industrial, derechos de autor será considerada y perseguida como un delito penal de comisión directa.</p>
                    <br></br><p className="color-gray-tex">&nbsp;<b>PROPIEDAD INTELECTUAL DE TERCEROS</b></p>
                    <p className="color-gray-tex">El usuario reconoce y se obliga a los términos del apartado tercero de este documento, para efectos de la titularidad de los derechos de uso, difusión y explotación de los de terceros respecto a los servicios y contenidos ofrecidos en las páginas vinculadas al Sitio.</p>
                    <br></br><p className="color-gray-tex">&nbsp;<b>MODIFICACIONES</b></p>
                    <p className="color-gray-tex"><b>PRESTTO</b> se reserva el derecho de modificar discrecionalmente el contenido y funcionalidad del Portal en cualquier momento, sin necesidad de previo aviso. <b>PRESTTO</b> podrá modificar los Términos y Condiciones Generales en cualquier momento haciendo públicos en el Sitio los términos modificados. Todos los términos modificados entrarán en vigor a los 10 (diez) días de su publicación. Dentro de los 5 (cinco) días siguientes a la publicación de las modificaciones introducidas, el Usuario deberá comunicar por e-mail si no acepta las mismas; en ese caso quedará disuelto el vínculo contractual y será inhabilitado como Usuario siempre que no tenga deudas pendientes. Vencido este plazo, se considerará que el Usuario acepta los nuevos términos y el contrato continuará vinculando a ambas partes.</p>
                    <br></br><p className="color-gray-tex"><b>5. PRIVACIDAD DE LA INFORMACIÓN</b></p>
                    <p className="color-gray-tex">Para utilizar los Servicios y Contenidos ofrecidos por <b>PRESTTO</b>, los Usuarios deberán facilitar determinados datos de carácter personal. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Para más información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, se puede consultar nuestro Aviso de Privacidad.</p>
                    <br></br><p className="color-gray-tex"><b>6. VIOLACIONES DEL SISTEMA O BASES DE DATOS</b></p>
                    <p className="color-gray-tex">No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatividad de <b>PRESTTO</b> como en la base de datos. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.</p>
                    <br></br><p className="color-gray-tex"><b>7. SUSPENSIÓN DE OPERACIONES</b></p>
                    <p className="color-gray-tex">Sin perjuicio de otras medidas, <b>PRESTTO</b> podrá advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o una publicación, aplicar una sanción que impacte negativamente en la reputación de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestación de sus Servicios si: (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones Generales y demás políticas de <b>PRESTTO</b>; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de <b>PRESTTO</b> en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier información proporcionada por el mismo fuere errónea; (e) PRESTTO entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las publicó.</p>
                    <br></br><p className="color-gray-tex"><b>RESPONSABILIDAD</b></p>
                    <p className="color-gray-tex"><b>PRESTTO</b> recomienda actuar con prudencia y sentido común al momento de realizar operaciones con otros Usuarios. En caso de que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a <b>PRESTTO</b> y a sus directores, gerentes, empleados, agentes, operadores, representantes y apoderados.</p>
                    <br></br><p className="color-gray-tex"><b>FALLAS EN EL SISTEMA</b></p>
                    <p className="color-gray-tex"><b>PRESTTO</b>  no se responsabiliza por cualquier daño, perjuicio o pérdida al Usuario causados por fallas en el sistema, en el servidor o en Internet. <b>PRESTTO</b>  tampoco será responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o navegación de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenido en el mismo, así como cualquier otra información enviada con el uso de medios electrónicos. Los Usuarios NO podrán imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en Internet. <b>PRESTTO</b>  no garantiza el acceso y uso continuado o ininterrumpido de su Sitio. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a <b>PRESTTO</b> ; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad. PRESTTO no será responsable por ningún error u omisión contenidos en su sitio web.</p>
                    <br></br><p className="color-gray-tex"><b>CONFIDENCIALIDAD</b></p>
                    <p className="color-gray-tex"><b>PRESTTO</b> se obliga expresamente a mantener confidencial la información que reciba del usuario que tenga dicho carácter conforme a legislación mexicana aplicable. <b>PRESTTO</b> no se obliga a guardar confidencialidad respecto a cualquier otra información señalada por el usuario durante cualquier interacción con el Sitio o en el proceso de aplicación y/u obtención de los servicios y contenidos, incluyendo más no limitándose a la información proporcionada en blogs, chats o medios afines.
                    <br></br>El usuario autoriza expresamente a <b>PRESTTO</b> a usar, publicar, o comunicar públicamente la información no considerada confidencial ingresada mediante el uso del Sitio, en términos de lo establecido en el artículo 109 de la Ley Federal de los Derechos de Autor</p>
                    <br></br><p className="color-gray-tex"><b>8. COOKIES</b></p>
                    <p className="color-gray-tex">El usuario que tenga acceso al Sitio acuerda recibir las Cookies que les transmitan los servidores de <b>PRESTTO</b>. “Cookie” significa un archivo de datos que se almacena en el disco duro de la computadora del usuario cuando este tiene acceso al Sitio. Las Cookies pueden contener información tal como la identificación proporcionada por el usuario o información para rastrear las páginas que el usuario ha visitado. Una Cookie no puede leer los datos o información del disco duro del usuario ni leer las Cookies creadas por otros sitios o páginas.</p>
                    <p className="color-gray-tex">Los presentes Términos y Condiciones Generales atañen únicamente a los servicios de <b>PRESTTO</b>. No tenemos control alguno sobre los sitios web mostrados como resultados de búsquedas o enlaces que se incluyen en nuestro Sitio. Es posible que estos sitios independientes envíen sus propias cookies u otros archivos a su equipo, recopilen datos o le soliciten que envíe información personal.</p>
                    <br></br><p className="color-gray-tex"><b>INDEMNIZACIÓN</b></p>
                    <p className="color-gray-tex">El Usuario indemnizará y mantendrá indemne a <b>PRESTTO</b>, sus filiales, empresas controladas y/o controlantes, directivos, administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o terceros por sus actividades en el Sitio o por su incumplimiento los Términos y Condiciones Generales y demás Políticas que se entienden incorporadas al presente o por la violación de cualesquiera leyes o derechos de terceros, incluyendo los honorarios de abogados en una cantidad razonable.</p>
                    <br></br><p className="color-gray-tex"><b>JURISDICCIÓN Y LEY APLICABLE</b></p>
                    <p className="color-gray-tex">Este acuerdo estará regido en todos sus puntos por las leyes mexicanas vigentes, en particular respecto de mensajes de datos, contratación y comercio electrónicos se regirá por lo dispuesto por la legislación federal respectiva.<br></br>
                    Cualquier controversia derivada de estos términos y condiciones, su existencia, validez, interpretación, alcance o cumplimiento, será sometida a las leyes aplicables y a los Tribunales competentes.<br></br>Para la interpretación, cumplimiento y ejecución de los Términos y Condiciones, las partes expresamente se someten a la jurisdicción de los tribunales federales competentes de la Ciudad de México, renunciando en consecuencia a cualquier fuero que debido a su domicilio presente o futuro pudiera corresponderles.</p>
                    <br></br><p className="color-gray-tex"><b>DOMICILIO</b></p>
                    <p className="color-gray-tex">Se fija como domicilio de <b>PRESTTO</b> Av. Nuevo León #213 - 602 Col. Condesa, Cuauhtémoc, C.P. 06100, Cuidad de México. </p>
                    <br></br><p className="color-gray-tex"><b>ADVERTENCIAS</b></p>
                    <p className="color-gray-tex">Incumplir tus obligaciones te puede generar comisiones e intereses moratorios. Contratar créditos por arriba de tu capacidad de pago puede afectar tu historial crediticio.</p>
                    <br></br><p className="color-gray-tex"><b>9. COBRANZA</b></p>
                    <p className="color-gray-tex"><b>PRESTTO</b> mantiene una comisión única por Gastos de cobranza que, en todo caso, no excederá de la cantidad de $200.00 (Doscientos pesos 00/100 MN) más I.V.A
                    <br></br>El Usuario podrá consultar los despachos de cobranza designados para las gestiones dentro del Portal <b>PRESTTO</b> o en <a href="https://www.prestto.mx/despachodecobranza/" target="self">https://www.prestto.mx/despachodecobranza/</a> , mismas que desarrollarán las gestiones de cobranza por medio de: correo electrónico; vía telefónica; correo postal y/o en el domicilio del deudor, las funciones de los agentes se limitarán a las del cobro por mora.</p>
                </div>
              </div>
            </div>
          </div>
         </section>
        <Footer location={this.props.history} />
      </div>
    );
  }
}

export default Terminosycondiciones;
